/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq;


import com.brook.example.jooq.tables.BackstageTbMessageLog;
import com.brook.example.jooq.tables.BackstageTbSSms;
import com.brook.example.jooq.tables.BackstageTbSSmsType;
import com.brook.example.jooq.tables.BackstageTbUOperatingLog;
import com.brook.example.jooq.tables.BackstageTbUUser;
import com.brook.example.jooq.tables.MenuInfo;
import com.brook.example.jooq.tables.MockUser;
import com.brook.example.jooq.tables.MonitorInfo;
import com.brook.example.jooq.tables.Test1;
import com.brook.example.jooq.tables.UserMenu;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CaishenBackstage extends SchemaImpl {

    private static final long serialVersionUID = -1319251625;

    /**
     * The reference instance of <code>caishen_backstage</code>
     */
    public static final CaishenBackstage CAISHEN_BACKSTAGE = new CaishenBackstage();

    /**
     * The table <code>caishen_backstage.backstage_tb_message_log</code>.
     */
    public final BackstageTbMessageLog BACKSTAGE_TB_MESSAGE_LOG = com.brook.example.jooq.tables.BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG;

    /**
     * The table <code>caishen_backstage.backstage_tb_s_sms</code>.
     */
    public final BackstageTbSSms BACKSTAGE_TB_S_SMS = com.brook.example.jooq.tables.BackstageTbSSms.BACKSTAGE_TB_S_SMS;

    /**
     * The table <code>caishen_backstage.backstage_tb_s_sms_type</code>.
     */
    public final BackstageTbSSmsType BACKSTAGE_TB_S_SMS_TYPE = com.brook.example.jooq.tables.BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE;

    /**
     * The table <code>caishen_backstage.backstage_tb_u_operating_log</code>.
     */
    public final BackstageTbUOperatingLog BACKSTAGE_TB_U_OPERATING_LOG = com.brook.example.jooq.tables.BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG;

    /**
     * The table <code>caishen_backstage.backstage_tb_u_user</code>.
     */
    public final BackstageTbUUser BACKSTAGE_TB_U_USER = com.brook.example.jooq.tables.BackstageTbUUser.BACKSTAGE_TB_U_USER;

    /**
     * The table <code>caishen_backstage.menu_info</code>.
     */
    public final MenuInfo MENU_INFO = com.brook.example.jooq.tables.MenuInfo.MENU_INFO;

    /**
     * The table <code>caishen_backstage.mock_user</code>.
     */
    public final MockUser MOCK_USER = com.brook.example.jooq.tables.MockUser.MOCK_USER;

    /**
     * The table <code>caishen_backstage.monitor_info</code>.
     */
    public final MonitorInfo MONITOR_INFO = com.brook.example.jooq.tables.MonitorInfo.MONITOR_INFO;

    /**
     * The table <code>caishen_backstage.test1</code>.
     */
    public final Test1 TEST1 = com.brook.example.jooq.tables.Test1.TEST1;

    /**
     * The table <code>caishen_backstage.user_menu</code>.
     */
    public final UserMenu USER_MENU = com.brook.example.jooq.tables.UserMenu.USER_MENU;

    /**
     * No further instances allowed
     */
    private CaishenBackstage() {
        super("caishen_backstage", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG,
            BackstageTbSSms.BACKSTAGE_TB_S_SMS,
            BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE,
            BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG,
            BackstageTbUUser.BACKSTAGE_TB_U_USER,
            MenuInfo.MENU_INFO,
            MockUser.MOCK_USER,
            MonitorInfo.MONITOR_INFO,
            Test1.TEST1,
            UserMenu.USER_MENU);
    }
}
