/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq;


import com.brook.example.jooq.tables.BackstageTbMessageLog;
import com.brook.example.jooq.tables.BackstageTbSSms;
import com.brook.example.jooq.tables.BackstageTbSSmsType;
import com.brook.example.jooq.tables.BackstageTbUOperatingLog;
import com.brook.example.jooq.tables.BackstageTbUUser;
import com.brook.example.jooq.tables.MenuInfo;
import com.brook.example.jooq.tables.MockUser;
import com.brook.example.jooq.tables.MonitorInfo;
import com.brook.example.jooq.tables.Test1;
import com.brook.example.jooq.tables.UserMenu;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>caishen_backstage</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BACKSTAGE_TB_MESSAGE_LOG_PRIMARY = Indexes0.BACKSTAGE_TB_MESSAGE_LOG_PRIMARY;
    public static final Index BACKSTAGE_TB_S_SMS_FK_SMS_TYPE_ID = Indexes0.BACKSTAGE_TB_S_SMS_FK_SMS_TYPE_ID;
    public static final Index BACKSTAGE_TB_S_SMS_PRIMARY = Indexes0.BACKSTAGE_TB_S_SMS_PRIMARY;
    public static final Index BACKSTAGE_TB_S_SMS_TYPE_PRIMARY = Indexes0.BACKSTAGE_TB_S_SMS_TYPE_PRIMARY;
    public static final Index BACKSTAGE_TB_U_OPERATING_LOG_PRIMARY = Indexes0.BACKSTAGE_TB_U_OPERATING_LOG_PRIMARY;
    public static final Index BACKSTAGE_TB_U_USER_PRIMARY = Indexes0.BACKSTAGE_TB_U_USER_PRIMARY;
    public static final Index MENU_INFO_INDEX2 = Indexes0.MENU_INFO_INDEX2;
    public static final Index MENU_INFO_PRIMARY = Indexes0.MENU_INFO_PRIMARY;
    public static final Index MOCK_USER_PRIMARY = Indexes0.MOCK_USER_PRIMARY;
    public static final Index MONITOR_INFO_PRIMARY = Indexes0.MONITOR_INFO_PRIMARY;
    public static final Index TEST1_PRIMARY = Indexes0.TEST1_PRIMARY;
    public static final Index USER_MENU_INDEX2 = Indexes0.USER_MENU_INDEX2;
    public static final Index USER_MENU_PRIMARY = Indexes0.USER_MENU_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index BACKSTAGE_TB_MESSAGE_LOG_PRIMARY = createIndex("PRIMARY", BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG, new OrderField[] { BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.ID }, true);
        public static Index BACKSTAGE_TB_S_SMS_FK_SMS_TYPE_ID = createIndex("fk_sms_type_id", BackstageTbSSms.BACKSTAGE_TB_S_SMS, new OrderField[] { BackstageTbSSms.BACKSTAGE_TB_S_SMS.SMS_TYPE_ID }, false);
        public static Index BACKSTAGE_TB_S_SMS_PRIMARY = createIndex("PRIMARY", BackstageTbSSms.BACKSTAGE_TB_S_SMS, new OrderField[] { BackstageTbSSms.BACKSTAGE_TB_S_SMS.SS_ID }, true);
        public static Index BACKSTAGE_TB_S_SMS_TYPE_PRIMARY = createIndex("PRIMARY", BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE, new OrderField[] { BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE.ST_ID }, true);
        public static Index BACKSTAGE_TB_U_OPERATING_LOG_PRIMARY = createIndex("PRIMARY", BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG, new OrderField[] { BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.OP_ID }, true);
        public static Index BACKSTAGE_TB_U_USER_PRIMARY = createIndex("PRIMARY", BackstageTbUUser.BACKSTAGE_TB_U_USER, new OrderField[] { BackstageTbUUser.BACKSTAGE_TB_U_USER.U_ID }, true);
        public static Index MENU_INFO_INDEX2 = createIndex("index2", MenuInfo.MENU_INFO, new OrderField[] { MenuInfo.MENU_INFO.MENU_NAME, MenuInfo.MENU_INFO.PARENT_NODE_ID }, false);
        public static Index MENU_INFO_PRIMARY = createIndex("PRIMARY", MenuInfo.MENU_INFO, new OrderField[] { MenuInfo.MENU_INFO.ID }, true);
        public static Index MOCK_USER_PRIMARY = createIndex("PRIMARY", MockUser.MOCK_USER, new OrderField[] { MockUser.MOCK_USER.ID }, true);
        public static Index MONITOR_INFO_PRIMARY = createIndex("PRIMARY", MonitorInfo.MONITOR_INFO, new OrderField[] { MonitorInfo.MONITOR_INFO.ID }, true);
        public static Index TEST1_PRIMARY = createIndex("PRIMARY", Test1.TEST1, new OrderField[] { Test1.TEST1.ID }, true);
        public static Index USER_MENU_INDEX2 = createIndex("index2", UserMenu.USER_MENU, new OrderField[] { UserMenu.USER_MENU.USER_ID, UserMenu.USER_MENU.MENU_ID }, false);
        public static Index USER_MENU_PRIMARY = createIndex("PRIMARY", UserMenu.USER_MENU, new OrderField[] { UserMenu.USER_MENU.ID }, true);
    }
}
