/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq;


import com.brook.example.jooq.tables.BackstageTbMessageLog;
import com.brook.example.jooq.tables.BackstageTbSSms;
import com.brook.example.jooq.tables.BackstageTbSSmsType;
import com.brook.example.jooq.tables.BackstageTbUOperatingLog;
import com.brook.example.jooq.tables.BackstageTbUUser;
import com.brook.example.jooq.tables.MenuInfo;
import com.brook.example.jooq.tables.MockUser;
import com.brook.example.jooq.tables.MonitorInfo;
import com.brook.example.jooq.tables.Test1;
import com.brook.example.jooq.tables.UserMenu;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in caishen_backstage
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>caishen_backstage.backstage_tb_message_log</code>.
     */
    public static final BackstageTbMessageLog BACKSTAGE_TB_MESSAGE_LOG = com.brook.example.jooq.tables.BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG;

    /**
     * The table <code>caishen_backstage.backstage_tb_s_sms</code>.
     */
    public static final BackstageTbSSms BACKSTAGE_TB_S_SMS = com.brook.example.jooq.tables.BackstageTbSSms.BACKSTAGE_TB_S_SMS;

    /**
     * The table <code>caishen_backstage.backstage_tb_s_sms_type</code>.
     */
    public static final BackstageTbSSmsType BACKSTAGE_TB_S_SMS_TYPE = com.brook.example.jooq.tables.BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE;

    /**
     * The table <code>caishen_backstage.backstage_tb_u_operating_log</code>.
     */
    public static final BackstageTbUOperatingLog BACKSTAGE_TB_U_OPERATING_LOG = com.brook.example.jooq.tables.BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG;

    /**
     * The table <code>caishen_backstage.backstage_tb_u_user</code>.
     */
    public static final BackstageTbUUser BACKSTAGE_TB_U_USER = com.brook.example.jooq.tables.BackstageTbUUser.BACKSTAGE_TB_U_USER;

    /**
     * The table <code>caishen_backstage.menu_info</code>.
     */
    public static final MenuInfo MENU_INFO = com.brook.example.jooq.tables.MenuInfo.MENU_INFO;

    /**
     * The table <code>caishen_backstage.mock_user</code>.
     */
    public static final MockUser MOCK_USER = com.brook.example.jooq.tables.MockUser.MOCK_USER;

    /**
     * The table <code>caishen_backstage.monitor_info</code>.
     */
    public static final MonitorInfo MONITOR_INFO = com.brook.example.jooq.tables.MonitorInfo.MONITOR_INFO;

    /**
     * The table <code>caishen_backstage.test1</code>.
     */
    public static final Test1 TEST1 = com.brook.example.jooq.tables.Test1.TEST1;

    /**
     * The table <code>caishen_backstage.user_menu</code>.
     */
    public static final UserMenu USER_MENU = com.brook.example.jooq.tables.UserMenu.USER_MENU;
}
