/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq.tables.records;


import com.brook.example.jooq.tables.BackstageTbUOperatingLog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackstageTbUOperatingLogRecord extends UpdatableRecordImpl<BackstageTbUOperatingLogRecord> implements Record9<Integer, String, String, String, String, Integer, String, String, String> {

    private static final long serialVersionUID = -1719294947;

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.op_id</code>. 主键
     */
    public void setOpId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.op_id</code>. 主键
     */
    public Integer getOpId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.op_type_name</code>. 类型名称
     */
    public void setOpTypeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.op_type_name</code>. 类型名称
     */
    public String getOpTypeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.op_desc</code>. 描述
     */
    public void setOpDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.op_desc</code>. 描述
     */
    public String getOpDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.op_gen_time</code>. 创建时间
     */
    public void setOpGenTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.op_gen_time</code>. 创建时间
     */
    public String getOpGenTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.ip_address</code>. IP地址
     */
    public void setIpAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.ip_address</code>. IP地址
     */
    public String getIpAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.user_id</code>. 外键
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.user_id</code>. 外键
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.str1</code>.
     */
    public void setStr1(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.str1</code>.
     */
    public String getStr1() {
        return (String) get(6);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.str2</code>.
     */
    public void setStr2(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.str2</code>.
     */
    public String getStr2() {
        return (String) get(7);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_u_operating_log.str3</code>.
     */
    public void setStr3(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_u_operating_log.str3</code>.
     */
    public String getStr3() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Integer, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Integer, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.OP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.OP_TYPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.OP_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.OP_GEN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.IP_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.STR1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.STR2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG.STR3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOpTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOpDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOpGenTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStr1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getStr2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getStr3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOpTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOpDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOpGenTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStr1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStr2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStr3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value1(Integer value) {
        setOpId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value2(String value) {
        setOpTypeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value3(String value) {
        setOpDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value4(String value) {
        setOpGenTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value5(String value) {
        setIpAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value7(String value) {
        setStr1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value8(String value) {
        setStr2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord value9(String value) {
        setStr3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbUOperatingLogRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BackstageTbUOperatingLogRecord
     */
    public BackstageTbUOperatingLogRecord() {
        super(BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG);
    }

    /**
     * Create a detached, initialised BackstageTbUOperatingLogRecord
     */
    public BackstageTbUOperatingLogRecord(Integer opId, String opTypeName, String opDesc, String opGenTime, String ipAddress, Integer userId, String str1, String str2, String str3) {
        super(BackstageTbUOperatingLog.BACKSTAGE_TB_U_OPERATING_LOG);

        set(0, opId);
        set(1, opTypeName);
        set(2, opDesc);
        set(3, opGenTime);
        set(4, ipAddress);
        set(5, userId);
        set(6, str1);
        set(7, str2);
        set(8, str3);
    }
}
