/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq.tables.records;


import com.brook.example.jooq.tables.BackstageTbSSmsType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackstageTbSSmsTypeRecord extends UpdatableRecordImpl<BackstageTbSSmsTypeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1567895008;

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms_type.st_id</code>.
     */
    public void setStId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms_type.st_id</code>.
     */
    public Integer getStId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms_type.st_type_name</code>. 发送短信类型，如(注册未绑卡的)
     */
    public void setStTypeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms_type.st_type_name</code>. 发送短信类型，如(注册未绑卡的)
     */
    public String getStTypeName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE.ST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE.ST_TYPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsTypeRecord value1(Integer value) {
        setStId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsTypeRecord value2(String value) {
        setStTypeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsTypeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BackstageTbSSmsTypeRecord
     */
    public BackstageTbSSmsTypeRecord() {
        super(BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE);
    }

    /**
     * Create a detached, initialised BackstageTbSSmsTypeRecord
     */
    public BackstageTbSSmsTypeRecord(Integer stId, String stTypeName) {
        super(BackstageTbSSmsType.BACKSTAGE_TB_S_SMS_TYPE);

        set(0, stId);
        set(1, stTypeName);
    }
}
