/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq.tables.records;


import com.brook.example.jooq.tables.BackstageTbMessageLog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackstageTbMessageLogRecord extends UpdatableRecordImpl<BackstageTbMessageLogRecord> implements Record10<Integer, Integer, String, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 736055034;

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.sms_id</code>. 短信内容类型id
     */
    public void setSmsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.sms_id</code>. 短信内容类型id
     */
    public Integer getSmsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.sms_name</code>. 短信纬度
     */
    public void setSmsName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.sms_name</code>. 短信纬度
     */
    public String getSmsName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.create_date</code>.
     */
    public void setCreateDate(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.create_date</code>.
     */
    public String getCreateDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.str1</code>. 备用字段1
     */
    public void setStr1(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.str1</code>. 备用字段1
     */
    public String getStr1() {
        return (String) get(4);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.str2</code>. 备用字段2
     */
    public void setStr2(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.str2</code>. 备用字段2
     */
    public String getStr2() {
        return (String) get(5);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.str3</code>. 备用字段3
     */
    public void setStr3(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.str3</code>. 备用字段3
     */
    public String getStr3() {
        return (String) get(6);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.str4</code>. 备用字段4
     */
    public void setStr4(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.str4</code>. 备用字段4
     */
    public String getStr4() {
        return (String) get(7);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.str5</code>. 备用字段5
     */
    public void setStr5(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.str5</code>. 备用字段5
     */
    public String getStr5() {
        return (String) get(8);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_message_log.success_count</code>.
     */
    public void setSuccessCount(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_message_log.success_count</code>.
     */
    public Integer getSuccessCount() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.SMS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.SMS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.STR1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.STR2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.STR3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.STR4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.STR5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG.SUCCESS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSmsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSmsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStr1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStr2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStr3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getStr4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getStr5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getSuccessCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSmsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSmsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStr1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStr2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStr3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStr4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStr5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getSuccessCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value2(Integer value) {
        setSmsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value3(String value) {
        setSmsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value4(String value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value5(String value) {
        setStr1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value6(String value) {
        setStr2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value7(String value) {
        setStr3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value8(String value) {
        setStr4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value9(String value) {
        setStr5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord value10(Integer value) {
        setSuccessCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbMessageLogRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BackstageTbMessageLogRecord
     */
    public BackstageTbMessageLogRecord() {
        super(BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG);
    }

    /**
     * Create a detached, initialised BackstageTbMessageLogRecord
     */
    public BackstageTbMessageLogRecord(Integer id, Integer smsId, String smsName, String createDate, String str1, String str2, String str3, String str4, String str5, Integer successCount) {
        super(BackstageTbMessageLog.BACKSTAGE_TB_MESSAGE_LOG);

        set(0, id);
        set(1, smsId);
        set(2, smsName);
        set(3, createDate);
        set(4, str1);
        set(5, str2);
        set(6, str3);
        set(7, str4);
        set(8, str5);
        set(9, successCount);
    }
}
