/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq.tables.records;


import com.brook.example.jooq.tables.BackstageTbSSms;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackstageTbSSmsRecord extends UpdatableRecordImpl<BackstageTbSSmsRecord> implements Record6<Integer, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = -887603197;

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms.ss_id</code>.
     */
    public void setSsId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms.ss_id</code>.
     */
    public Integer getSsId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms.ss_sms_name</code>. 要发送的短信内容
     */
    public void setSsSmsName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms.ss_sms_name</code>. 要发送的短信内容
     */
    public String getSsSmsName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms.ss_gen_time</code>. 创建时间
     */
    public void setSsGenTime(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms.ss_gen_time</code>. 创建时间
     */
    public String getSsGenTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms.ss_update_time</code>. 更新时间
     */
    public void setSsUpdateTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms.ss_update_time</code>. 更新时间
     */
    public String getSsUpdateTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms.ss_status</code>.
     */
    public void setSsStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms.ss_status</code>.
     */
    public Integer getSsStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>caishen_backstage.backstage_tb_s_sms.sms_type_id</code>. 短信类型外键
     */
    public void setSmsTypeId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>caishen_backstage.backstage_tb_s_sms.sms_type_id</code>. 短信类型外键
     */
    public Integer getSmsTypeId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BackstageTbSSms.BACKSTAGE_TB_S_SMS.SS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BackstageTbSSms.BACKSTAGE_TB_S_SMS.SS_SMS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BackstageTbSSms.BACKSTAGE_TB_S_SMS.SS_GEN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BackstageTbSSms.BACKSTAGE_TB_S_SMS.SS_UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return BackstageTbSSms.BACKSTAGE_TB_S_SMS.SS_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return BackstageTbSSms.BACKSTAGE_TB_S_SMS.SMS_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSsSmsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSsGenTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSsUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getSsStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSmsTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSsSmsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSsGenTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSsUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSsStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSmsTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsRecord value1(Integer value) {
        setSsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsRecord value2(String value) {
        setSsSmsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsRecord value3(String value) {
        setSsGenTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsRecord value4(String value) {
        setSsUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsRecord value5(Integer value) {
        setSsStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsRecord value6(Integer value) {
        setSmsTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BackstageTbSSmsRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BackstageTbSSmsRecord
     */
    public BackstageTbSSmsRecord() {
        super(BackstageTbSSms.BACKSTAGE_TB_S_SMS);
    }

    /**
     * Create a detached, initialised BackstageTbSSmsRecord
     */
    public BackstageTbSSmsRecord(Integer ssId, String ssSmsName, String ssGenTime, String ssUpdateTime, Integer ssStatus, Integer smsTypeId) {
        super(BackstageTbSSms.BACKSTAGE_TB_S_SMS);

        set(0, ssId);
        set(1, ssSmsName);
        set(2, ssGenTime);
        set(3, ssUpdateTime);
        set(4, ssStatus);
        set(5, smsTypeId);
    }
}
