/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq.tables.records;


import com.brook.example.jooq.tables.MenuInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MenuInfoRecord extends UpdatableRecordImpl<MenuInfoRecord> implements Record8<Integer, String, String, Integer, Integer, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = 1409217937;

    /**
     * Setter for <code>caishen_backstage.menu_info.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>caishen_backstage.menu_info.menu_name</code>. 菜单名称
     */
    public void setMenuName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.menu_name</code>. 菜单名称
     */
    public String getMenuName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>caishen_backstage.menu_info.menu_url</code>. 菜单跳转地址
     */
    public void setMenuUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.menu_url</code>. 菜单跳转地址
     */
    public String getMenuUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>caishen_backstage.menu_info.parent_node_id</code>. 父节点id
     */
    public void setParentNodeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.parent_node_id</code>. 父节点id
     */
    public Integer getParentNodeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>caishen_backstage.menu_info.is_delete</code>. 状态   0-使用 1－删除
     */
    public void setIsDelete(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.is_delete</code>. 状态   0-使用 1－删除
     */
    public Integer getIsDelete() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>caishen_backstage.menu_info.create_date</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>caishen_backstage.menu_info.update_date</code>. 修改时间
     */
    public void setUpdateDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.update_date</code>. 修改时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>caishen_backstage.menu_info.sort_key</code>. 菜单排序
     */
    public void setSortKey(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>caishen_backstage.menu_info.sort_key</code>. 菜单排序
     */
    public Integer getSortKey() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MenuInfo.MENU_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MenuInfo.MENU_INFO.MENU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MenuInfo.MENU_INFO.MENU_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MenuInfo.MENU_INFO.PARENT_NODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MenuInfo.MENU_INFO.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MenuInfo.MENU_INFO.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MenuInfo.MENU_INFO.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return MenuInfo.MENU_INFO.SORT_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMenuUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getParentNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getSortKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMenuUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getParentNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getSortKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value2(String value) {
        setMenuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value3(String value) {
        setMenuUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value4(Integer value) {
        setParentNodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value5(Integer value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value6(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value7(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord value8(Integer value) {
        setSortKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MenuInfoRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MenuInfoRecord
     */
    public MenuInfoRecord() {
        super(MenuInfo.MENU_INFO);
    }

    /**
     * Create a detached, initialised MenuInfoRecord
     */
    public MenuInfoRecord(Integer id, String menuName, String menuUrl, Integer parentNodeId, Integer isDelete, Timestamp createDate, Timestamp updateDate, Integer sortKey) {
        super(MenuInfo.MENU_INFO);

        set(0, id);
        set(1, menuName);
        set(2, menuUrl);
        set(3, parentNodeId);
        set(4, isDelete);
        set(5, createDate);
        set(6, updateDate);
        set(7, sortKey);
    }
}
