/*
 * This file is generated by jOOQ.
*/
package com.brook.example.jooq.tables.records;


import com.brook.example.jooq.tables.MonitorInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MonitorInfoRecord extends UpdatableRecordImpl<MonitorInfoRecord> implements Record9<Long, String, String, Boolean, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1912243189;

    /**
     * Setter for <code>caishen_backstage.monitor_info.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.name</code>. 应用名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.name</code>. 应用名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.url</code>. 监控服务地址
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.url</code>. 监控服务地址
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.is_delete</code>. 删除标记 0:未删除,1:删除
     */
    public void setIsDelete(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.is_delete</code>. 删除标记 0:未删除,1:删除
     */
    public Boolean getIsDelete() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.error_result</code>. 返回结果信息
     */
    public void setErrorResult(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.error_result</code>. 返回结果信息
     */
    public String getErrorResult() {
        return (String) get(4);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.desc</code>. 描述
     */
    public void setDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.desc</code>. 描述
     */
    public String getDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.status</code>. 监控状态
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.status</code>. 监控状态
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>caishen_backstage.monitor_info.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>caishen_backstage.monitor_info.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, Boolean, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, Boolean, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MonitorInfo.MONITOR_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MonitorInfo.MONITOR_INFO.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MonitorInfo.MONITOR_INFO.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return MonitorInfo.MONITOR_INFO.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MonitorInfo.MONITOR_INFO.ERROR_RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MonitorInfo.MONITOR_INFO.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MonitorInfo.MONITOR_INFO.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return MonitorInfo.MONITOR_INFO.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return MonitorInfo.MONITOR_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getErrorResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getErrorResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value3(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value4(Boolean value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value5(String value) {
        setErrorResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value6(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value8(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord value9(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MonitorInfoRecord values(Long value1, String value2, String value3, Boolean value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MonitorInfoRecord
     */
    public MonitorInfoRecord() {
        super(MonitorInfo.MONITOR_INFO);
    }

    /**
     * Create a detached, initialised MonitorInfoRecord
     */
    public MonitorInfoRecord(Long id, String name, String url, Boolean isDelete, String errorResult, String desc, String status, Timestamp createTime, Timestamp updateTime) {
        super(MonitorInfo.MONITOR_INFO);

        set(0, id);
        set(1, name);
        set(2, url);
        set(3, isDelete);
        set(4, errorResult);
        set(5, desc);
        set(6, status);
        set(7, createTime);
        set(8, updateTime);
    }
}
