server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.brook.example.security: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:brook_admin;MODE=mysql;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update # create-drop 不会创建数据


