spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;DB_CLOSE_DELAY=-1
    username: sa
    password:
    type: org.apache.tomcat.jdbc.pool.XADataSource
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update